baseURL = "https://bitcast.co.za/"
languageCode = "en-za"
title = "BitCast"
theme = "hugo-universal-theme"

[params]
email = "info@bitcast.co.za"
about_us = "BitCast provides broadcast IT solutions and studio services"
copyright = "Copyright (c) 2018, BitCast; all rights reserved."
logo = "img/logo.png"
logo_small = "img/logo.png"

[params.features]
enable = true

[[menu.main]]
name = "Home"
url  = "/"
weight = 1

[[menu.main]]
name = "Contact"
url  = "/contact/"
weight = 4
