baseURL = "https://bitcast.co.za/"
languageCode = "en-za"
title = "Bitcast"
theme = "hugo-universal-theme"

[params]
about_us = "Bitcast provides personalised IT consulting and solutions"
copyright = "Copyright (c) 2018-2023, Bitcast (Pty) Ltd 2019/140776/07; all rights reserved."
logo = "img/logo.png"
logo_small = "img/logo.png"
date_format = ""

[params.carousel]
enable = true

[params.features]
enable = true

[params.clients]
enable = true
title = "Our Partners"
subtitle = "We have proudly worked with the following companies."

[[menu.main]]
name = "Home"
url  = "/"
weight = 1

[[menu.main]]
name = "Contact"
url  = "/contact/"
weight = 4

[markup.goldmark.renderer]
unsafe = true
