baseURL = "https://bitcast.co.za/"
languageCode = "en-za"
title = "Bitcast"
theme = "hugo-universal-theme"

[params]
email = "f/xrgoklaw"
about_us = "Bitcast provides IT solutions and broadcast studio services"
copyright = "Copyright (c) 2018-2020, Bitcast (Pty) Ltd 2019/140776/07; all rights reserved."
logo = "img/logo.png"
logo_small = "img/logo.png"
date_format = ""

[params.carousel]
enable = true

[params.features]
enable = true

[params.clients]
enable = true
title = "Our Partners"
subtitle = "We have proudly worked with the following companies."

[[menu.main]]
name = "Home"
url  = "/"
weight = 1

[[menu.main]]
name = "COVID-19"
url  = "https://sacoronavirus.co.za/"
weight = 2

[[menu.main]]
name = "Contact"
url  = "/contact/"
weight = 4
