name: Housekeeping

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: {}

jobs:
  find_broken_links:
    if: github.repository_owner == 'bitcastza'
    name: Find broken links

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check Links
        id: lychee
        uses: lycheeverse/lychee-action@v1.5.2
        with:
          args: >-
            '**/*.md'
            --require-https
            --exclude-all-private
            --exclude-mail
          fail: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

